export const MaskType = {
    squircle: 'squircle',
    heart: 'heart',
    hexagon: 'hexagon',
    hexagon2: 'hexagon-2',
    decagon: 'decagon',
    pentagon: 'pentagon',
    diamond: 'diamond',
    square: 'square',
    circle: 'circle',
    parallelogram: 'parallelogram',
    parallelogram2: 'parallelogram-2',
    parallelogram3: 'parallelogram-3',
    parallelogram4: 'parallelogram-4',
    star: 'star',
    star2: 'star-2',
    triangle: 'triangle',
    triangle2: 'triangle-2',
    triangle3: 'triangle-3',
    triangle4: 'triangle-4',
};
