import type { Config } from 'tailwindcss';

export const TAILWIND_CONFIG: Config = {
    content: ['./src/**/*.{svelte,js,ts}'],
    theme: {
        extend: {
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                primary: 'hsla(var(--primary, 259, 94%, 51%), <alpha-value>)',
                'primary-content': 'hsla(var(--primary-content, 0, 0%, 100%), <alpha-value>)',
                'primary-focus': 'hsla(var(--primary-focus, 259, 94%, 41%), <alpha-value>)',
                secondary: 'hsla(var(--secondary, 314, 100%, 47%), <alpha-value>)',
                'secondary-content': 'hsla(var(--secondary-content, 0, 0%, 100%), <alpha-value>)',
                'secondary-focus': 'hsla(var(--secondary-focus, 314, 100%, 38%), <alpha-value>)',
                accent: 'hsla(var(--accent, 174, 60%, 51%), <alpha-value>)',
                'accent-content': 'hsla(var(--accent-content, 175, 44%, 15%), <alpha-value>)',
                'accent-focus': 'hsla(var(--accent-focus, 174, 60%, 41%), <alpha-value>)',
                neutral: 'hsla(var(--neutral, 219, 14%, 28%), <alpha-value>)',
                'neutral-content': 'hsla(var(--neutral-content, 0, 0%, 100%), <alpha-value>)',
                'neutral-focus': 'hsla(var(--neutral-focus, 219, 14%, 22%), <alpha-value>)',
                'base-100': 'hsla(var(--base-100, 0, 0%, 100%), <alpha-value>)',
                'base-200': 'hsla(var(--base-200, 0, 0%, 90%), <alpha-value>)',
                'base-300': 'hsla(var(--base-300, 0, 0%, 81%), <alpha-value>)',
                'base-content': 'hsla(var(--base-content, 215, 28%, 17%), <alpha-value>)',
                success: 'hsla(var(--success, 158, 64%, 52%), <alpha-value>)',
                'success-content': 'hsla(var(--success-content, 158, 100%, 10%), <alpha-value>)',
                'success-focus': 'hsla(var(--success-focus, 158, 64%, 42%), <alpha-value>)',
                info: 'hsla(var(--info, 198, 93%, 60%), <alpha-value>)',
                'info-content': 'hsla(var(--info-content, 198, 100%, 12%), <alpha-value>)',
                'info-focus': 'hsla(var(--info-focus, 198, 93%, 48%), <alpha-value>)',
                warning: 'hsla(var(--warning, 43, 96%, 56%), <alpha-value>)',
                'warning-content': 'hsla(var(--warning-content, 43, 100%, 11%), <alpha-value>)',
                'warning-focus': 'hsla(var(--warning-focus, 43, 96%, 45%), <alpha-value>)',
                error: 'hsla(var(--error, 0, 91%, 71%), <alpha-value>)',
                'error-content': 'hsla(var(--error-content, 0, 100%, 14%), <alpha-value>)',
                'error-focus': 'hsla(var(--error-focus, 0, 91%, 57%), <alpha-value>)',
            },
        },
    },
};
