import type { Config } from 'tailwindcss';

export const TAILWIND_CONFIG: Config = {
    content: ['./src/**/*.{svelte,js,ts}'],
    theme: {
        extend: {
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                primary: 'rgb(var(--primary, 87 13 248) / <alpha-value>)',
                'primary-content': 'rgb(var(--primary-content, 255 255 255) / <alpha-value>)',
                'primary-focus': 'rgb(var(--primary-focus, 68 6 203) / <alpha-value>)',
                secondary: 'rgb(var(--secondary, 240 0 184) / <alpha-value>)',
                'secondary-content': 'rgb(var(--secondary-content, 255 255 255) / <alpha-value>)',
                'secondary-focus': 'rgb(var(--secondary-focus, 192 0 147) / <alpha-value>)',
                accent: 'rgb(var(--accent, 55 205 190) / <alpha-value>)',
                'accent-content': 'rgb(var(--accent-content, 22 56 53) / <alpha-value>)',
                'accent-focus': 'rgb(var(--accent-focus, 42 166 154) / <alpha-value>)',
                neutral: 'rgb(var(--neutral, 61 68 81) / <alpha-value>)',
                'neutral-content': 'rgb(var(--neutral-content, 255 255 255) / <alpha-value>)',
                'neutral-focus': 'rgb(var(--neutral-focus, 49 54 65) / <alpha-value>)',
                'base-100': 'rgb(var(--base-100, 255 255 255) / <alpha-value>)',
                'base-200': 'rgb(var(--base-200, 230 230 230) / <alpha-value>)',
                'base-300': 'rgb(var(--base-300, 207 207 207) / <alpha-value>)',
                'base-content': 'rgb(var(--base-content, 31 41 55) / <alpha-value>)',
                success: 'rgb(var(--success, 54 211 153) / <alpha-value>)',
                'success-content': 'rgb(var(--success-content, 0 53 33) / <alpha-value>)',
                'success-focus': 'rgb(var(--success-focus, 42 166 154) / <alpha-value>)',
                info: 'rgb(var(--info, 58 191 248) / <alpha-value>)',
                'info-content': 'rgb(var(--info-content, 0 43 61) / <alpha-value>)',
                'info-focus': 'rgb(var(--info-focus, 8 168 236) / <alpha-value>)',
                warning: 'rgb(var(--warning, 251 189 35) / <alpha-value>)',
                'warning-content': 'rgb(var(--warning-content, 57 41 0) / <alpha-value>)',
                'warning-focus': 'rgb(var(--warning-focus, 225 161 4) / <alpha-value>)',
                error: 'rgb(var(--error, 248 114 114) / <alpha-value>)',
                'error-content': 'rgb(var(--error-content, 72 0 0) / <alpha-value>)',
                'error-focus': 'rgb(var(--error-focus, 245 45 45) / <alpha-value>)',
            },
        },
    },
};
