/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MarkupInput {
	content: string;
	filename: string;
}
export interface MarkupResult {
	code?: string;
	dependencies?: Array<string>;
}
export function markup(input: MarkupInput): MarkupResult;
