/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PreprocessorOptions {
    screenSizes: Record<string, string>;
    includeDefaults: boolean;
    includeAsGlobal: boolean;
}
export interface MarkupPreprocessorInput {
    content: string;
    filename?: string;
}
export interface PreprocessorInput {
    content: string;
    attributes: Record<string, string>;
    markup: string;
    filename?: string;
}
export interface Processed {
    code: string;
    map?: string;
    dependencies?: Array<string>;
}
export class PreprocessorGroup {
    constructor(options?: PreprocessorOptions | undefined | null);
    markup(input: MarkupPreprocessorInput): Processed;
    script(input: PreprocessorInput): Processed;
    style(input: PreprocessorInput): Processed;
}
