export const MAIN_MODULE_NAME = '@svelte-daisyui/core';
export const SCRIPT_REGEX = /<script(\s[^]*?)?(?:>([^]*?)<\/script>|\/>)/gi;
export const STYLE_REGEX = /<style(\s[^]*?)?(?:>([^]*?)<\/style>|\/>)/gi;
export const SVELTE_COMMENT_REGEX = /<!--[^]*?-->/g;
export const SCRIPT_COMMENT_REGEX = /\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm;
//import(?:["'\s]*([\w*{}\n, ]+)from\s*)?["'\s](.*[@\w/_-]+)["'\s].*
export const IMPORT_STATEMENT_REGEX = (modulePath: string) =>
    new RegExp(`import(?:["'\s]*([\w*{}\n, ]+)from\s*)?["'\s]${modulePath}\/?([^ \n\t/]+)?["']`, 'g');
export const COMPONENT_NAMES = [
    'Alert',
    'Artboard',
    'Avatar',
    'AvatarGroup',
    'Badge',
    'BreadcrumbGroup',
    'BreadcrumbItem',
    'Button',
    'ButtonGroup',
    'Card',
    'CarouselGroup',
    'CarouselItem',
    'Checkbox',
    'Code',
    'Collapse',
    'CollapseContent',
    'CollapseTitle',
    'Countdown',
    'Divider',
    'Drawer',
    'Dropdown',
    'DropdownContent',
    'Footer',
    'Fragment',
    'Hero',
    'HeroContent',
    'Icon',
    'IndicatorGroup',
    'IndicatorItem',
    'InputGroup',
    'Kbd',
    'Link',
    'Mask',
    'Menu',
    'MenuItem',
    'MenuTitle',
    'Modal',
    'Navbar',
    'NavbarCenter',
    'NavbarEnd',
    'NavbarStart',
    'Portal',
    'Progress',
    'RadialProgress',
    'Radio',
    'Range',
    'Rating',
    'Select',
    'Stack',
    'StatsGroup',
    'StatsItem',
    'StatsItemActions',
    'StatsItemDescription',
    'StatsItemFigure',
    'StatsItemTitle',
    'StatsItemValue',
    'StepsGroup',
    'StepsItem',
    'Swap',
    'Table',
    'TableBody',
    'TableCell',
    'TableFooter',
    'TableHeader',
    'TableHeaderCell',
    'TableRow',
    'TabsGroup',
    'TabsItem',
    'Textarea',
    'Toggle',
    'Tooltip',
    'TooltipWrapper',
    'Window',
] as const;
